version: "2"
services:

  postgresql:
    build: ../postgres/
    container_name: sample-postgres
    volumes:
      - ${samplep}/sample-postgresql/data:/var/lib/postgresql/data
    ports:
      - 10432:5432
    environment:
      POSTGRES_INITDB_ARGS: --encoding=UTF8 --locale=en_US.UTF-8 --lc-ctype=ru_RU.UTF-8 --lc-collate=C
      POSTGRES_DB: sample
      POSTGRES_USER: sample
      POSTGRES_PASSWORD: sample

  sample-asyncpg:
    build:
      dockerfile: ${samplep}/sample-asyncpg/Dockerfile
      context: ${samplep}/sample-asyncpg
      args:
        sample: ${samplep}/sample-asyncpg
    container_name: sample-asyncpg
    links:
      - "postgresql:docker-postgresql"
    volumes:
      - ${samplep}/sample-asyncpg:/app
    depends_on:
      - postgresql
